name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: |
        npm run lint
        npm run test:jest
        npm test
        
    - name: Extract version
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          VERSION="${{ github.event.inputs.version }}"
        else
          VERSION="${GITHUB_REF#refs/tags/}"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Extracted version: $VERSION"
        
    - name: Update package.json version
      run: |
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        TARGET_VERSION="${{ steps.version.outputs.version }}"
        TARGET_VERSION=${TARGET_VERSION#v}  # Remove 'v' prefix if present
        
        echo "Current version: $CURRENT_VERSION"
        echo "Target version: $TARGET_VERSION"
        
        if [ "$CURRENT_VERSION" != "$TARGET_VERSION" ]; then
          echo "Updating version from $CURRENT_VERSION to $TARGET_VERSION"
          npm version $TARGET_VERSION --no-git-tag-version
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json
          git commit -m "Bump version to $TARGET_VERSION" || echo "No changes to commit"
        else
          echo "Version already matches target version, skipping update"
        fi
        
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}
          ghcr.io/${{ github.repository }}:latest
        platforms: linux/amd64
        
    - name: Prepare release notes
      id: changelog
      run: |
        if [ -f "CHANGELOG.md" ]; then
          echo "Using existing CHANGELOG.md"
          # Extract the section for this version
          VERSION="${{ steps.version.outputs.version }}"
          VERSION=${VERSION#v}  # Remove 'v' prefix if present
          
          # Find the section for this version in CHANGELOG.md
          if grep -q "\[$VERSION\]" CHANGELOG.md; then
            echo "Found changelog entry for version $VERSION"
            # Extract from [version] to next [version] or end of file
            sed -n "/\[$VERSION\]/,/^## \[/p" CHANGELOG.md | sed '$d' > release_notes.md
          else
            echo "No changelog entry found for version $VERSION, using git log"
            echo "## What's Changed" > release_notes.md
            echo "" >> release_notes.md
            git log --pretty=format:"- %s (%h)" --since="$(git describe --tags --abbrev=0 HEAD^)" >> release_notes.md || echo "- Initial release" >> release_notes.md
            echo "" >> release_notes.md
            echo "**Full Changelog**: https://github.com/${{ github.repository }}/compare/${{ steps.version.outputs.version }}...HEAD" >> release_notes.md
          fi
        else
          echo "No CHANGELOG.md found, generating from git log"
          echo "## What's Changed" > release_notes.md
          echo "" >> release_notes.md
          git log --pretty=format:"- %s (%h)" --since="$(git describe --tags --abbrev=0 HEAD^)" >> release_notes.md || echo "- Initial release" >> release_notes.md
          echo "" >> release_notes.md
          echo "**Full Changelog**: https://github.com/${{ github.repository }}/compare/${{ steps.version.outputs.version }}...HEAD" >> release_notes.md
        fi
        
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.version }}
        release_name: Release ${{ steps.version.outputs.version }}
        body_path: release_notes.md
        draft: false
        prerelease: ${{ contains(steps.version.outputs.version, 'beta') || contains(steps.version.outputs.version, 'alpha') || contains(steps.version.outputs.version, 'rc') }}
        
    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./package.json
        asset_name: package.json
        asset_content_type: application/json
